### ISSUE TITLE
bulker init is broken

### ISSUE THREAD

**Issue by nsheff** [databio/bulker#21]
```
rm bulker_config.yaml 
nsheff@puma:~$ bulker init -c $BULKERCFG
Guessing container engine is docker.
Waiting for file lock: /home/nsheff/.local/lib/python3.5/site-packages/bulker/templates/lock.bulker_config.yaml ....Traceback (most recent call last):
  File "/home/nsheff/.local/bin/bulker", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/bulker/bulker.py", line 496, in main
    bulker_init(bulkercfg, DEFAULT_CONFIG_FILEPATH, args.engine)
  File "/home/nsheff/.local/lib/python3.5/site-packages/bulker/bulker.py", line 228, in bulker_init
    bulker_config = yacman.YacAttMap(filepath=template_config_path, writable=True)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 84, in __init__
    _make_rw(filepath, wait_max)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 265, in _make_rw
    _wait_for_lock(lock_path, wait_max)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 227, in _wait_for_lock
    raise RuntimeError("The maximum wait time has been reached and the lock file still exists.")
RuntimeError: The maximum wait time has been reached and the lock file still exists.
```

**Comment by nsheff** [comment]
This was caused by a previous error that wasn't properly cleaned up. I just had to manually remove the lock:

```
rm /home/nsheff/.local/lib/python3.5/site-packages/bulker/templates/lock.bulker_config.yaml
```

So, it's not a problem after all.
