### ISSUE TITLE
AttributeError: default_namespace

### ISSUE THREAD

**Issue by nsheff** [databio/bulker#22]
not sure what's causing this error:

```
bulker activate databio/lab
Bulker config: /project/shefflab/bulker/bulker_config_rivanna.yaml
Traceback (most recent call last):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 31, in __getattr__
    v = super(PathExAttMap, self).__getattribute__(item)
AttributeError: 'YacAttMap' object has no attribute 'default_namespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'default_namespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 34, in __getattr__
    return self.__getitem__(item, expand)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'default_namespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/bulker", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/bulker/bulker.py", line 521, in main
    cratelist = parse_registry_paths(args.crate_registry_paths, bulker_config.bulker.default_namespace)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 38, in __getattr__
    raise AttributeError(item)
AttributeError: default_namespace
```

bulker --version
bulker 0.2.3

yacman is 0.6.0

**Comment by nsheff** [comment]
I needed to re-create the bulker configuration file, which had been created using an earlier version of bulker. it was just missing the

`default_namespace` attribute.
