### ISSUE TITLE
NameError: name 'create_folder' is not defined

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/bulker#26]
**on `dev` branch**
```
[mstolarczyk@MichalsMBP test_genomes]: export BULKERCFG="~/bulker_config.yaml"
[mstolarczyk@MichalsMBP test_genomes]: bulker init -c $BULKERCFG
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/bulker", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/bulker.py", line 611, in main
    _is_writable(os.path.dirname(bulkercfg), check_exist=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/bulker.py", line 196, in _is_writable
    elif create_folder:
NameError: name 'create_folder' is not defined
```

**Comment by nsheff** [comment]
should have been `crate_folder` maybe?

**Comment by michalstolarczyk** [comment]
the variable name does not match the one in the function signature:

https://github.com/databio/bulker/blob/81caa9b56b7fe5f6bd8222beef256fc259ff9fd4/bulker/bulker.py#L180-L196

**Comment by michalstolarczyk** [comment]
can you grant me write permissions here? I can squash bugs instead of reporting

**Comment by nsheff** [comment]
done.

**Comment by nsheff** [comment]
I think _is_writable should import from ubiquerg actually...
