### ISSUE TITLE
KeyError: 'singularity_fullpath'

### ISSUE THREAD

**Issue by stolarczyk** [databio/bulker#59]
might be related to #53 

```
[mstolarczyk@MichalsMBP ~]: bulker load -r -b databio/lab
Using default config. No config found in env var: BULKERCFG
Bulker config: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/templates/bulker_config.yaml
Building images with template: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/templates/docker_build.jinja2
Removing all executables in: /Users/mstolarczyk/bulker_crates/databio/lab/default
Importing crate 'bulker/biobase:default' from '/Users/mstolarczyk/bulker_crates/bulker/biobase/default'.
RELEASE_3_11: Pulling from bioconductor/bioconductor_docker
23884877105a: Already exists 
bc38caa0f5b9: Already exists 
2910811b6c42: Already exists 
36505266dcc6: Already exists 
d21d194790d1: Pull complete 
3821ac91f817: Pull complete 
3334418e8171: Pull complete 
63380217dd8a: Pull complete 
1319b4ef3651: Pull complete 
94b33093acf7: Pull complete 
4d08753fb4b6: Pull complete 
ee9dbe765945: Pull complete 
4ed5d6c602cd: Pull complete 
7abf5c9d7995: Pull complete 
9a594bb377a3: Pull complete 
49dc1b5126c8: Pull complete 
ef45bfc7da05: Pull complete 
57e43e3bc013: Pull complete 
ff6b3c64cfd9: Pull complete 
Digest: sha256:ed70db2dd7746fd3e3edcc5d36e0c24860da0fb7f1270d7f7174259380ef7bcc
Status: Downloaded newer image for bioconductor/bioconductor_docker:RELEASE_3_11
docker.io/bioconductor/bioconductor_docker:RELEASE_3_11
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'singularity_fullpath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/bulker", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/bulker.py", line 870, in main
    force=args.force)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/bulker.py", line 426, in bulker_load
    _LOGGER.info("Container available at: {cmd}".format(cmd=pkg["singularity_fullpath"]))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'singularity_fullpath'

```

I just installed bulker v0.5.0 and tried to load a crate using the config that shipped with bulker. Commenting out the line that shows up in the traceback helped:

https://github.com/databio/bulker/blob/3394c35b8f7738c285d1af9e913b5830a3e3b7f5/bulker/bulker.py#L426

**Comment by nsheff** [comment]
I think I solved this. it was expecting if you asked to build that you were using singularity. now it correctly handles it if you were using docker.
